version: '3.7'

services:

  sqlnodeplate:
    image: sqlnodeplate
    restart: unless-stopped
    container_name: sqlnodeplate
    build: ./node/
    ports:
      - 3001:3001
      
  db:
    image: mysql
    restart: unless-stopped
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    build: ./database/
    ports:
      - 3306:3306

  openalpr:
    image: fauslyfox110/openalpr-platenet:firsttry
    restart: unless-stopped
    container_name: openalpr
    ports:
      - 5000:5000

  caddy:
    container_name: caddy
    image: abdulsalamdocker/caddy:1.0.3-no-stats
    restart: unless-stopped
    env_file:
      - ./caddyrp/env/caddy.env
    volumes:
      - ./caddyrp/Caddyfile:/etc/Caddyfile:ro
      - $HOME/.caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
      - 2015:2015

  