version: '3.7'

services:

  sqlnodeplate:
    image: sqlnodeplate
    restart: unless-stopped
    container_name: sqlnodeplate
    build: ./node/
    ports:
      - 3001:3001
    networks:
      default:
        external:
          name: my-net

  testapi:
    container_name: testapi
    build: ./nodetest/
    ports:
      - 4000:4000
    networks:
      default:
        external:
          name: my-net
      
  db:
    image: mysql
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    build: ./database/
    ports:
      - 3306:3306
    networks:
      default:
        external:
          name: my-net

  openalpr:
    image: fauslyfox110/openalpr-platenet:firsttry
    restart: unless-stopped
    container_name: openalpr
    ports:
      - 5000:5000
    networks:
      default:
        external:
          name: my-net

  caddy:
    container_name: caddy
    image: abdulsalamdocker/caddy:1.0.3-no-stats
    restart: unless-stopped
    env_file:
      - ./caddyrp/env/caddy.env
    volumes:
      - ./caddyrp/Caddyfile:/etc/Caddyfile:ro
      - $HOME/.caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    networks:
      default:
        external:
          name: my-net

  